### ISSUE TITLE
Outsource HTML from grandeljaydhl::nationalCostsSet()

### ISSUE THREAD

**Issue by RobinTheHood** [grandeljay/modified-dhl#1]
In static method grandeljaydhl::nationalCostsSet() is a lot of HTML. Maybe it is a good idea to separate HTML und PHP and put HTML in an extra file?

**Comment by grandeljay** [comment]
I've been thinking about this a lot and have a different thoughts you might be able to help me with:

1. Refactor all non-native methods into a separate class (only keeping `__construct`, `install`, `remove`, `quote`)
2. Refactor all methods used as a `set_function` into a separate class, only used for `set_functions`. Since this are so far only used for HTML output it would remove a bunch of code but ultimately `grandeljaydhl::nationalCostsSet` would still not be in a separate file

**Comment by grandeljay** [comment]
Thank you for all your help! I've added a bunch of classes and refactored large parts of the code.
